### ISSUE TITLE
RedisTransport on close

### ISSUE THREAD

**Issue by progmancod** [bpolaszek/freddie#24]
Using the RedisTransport Pub/Sub, if there is an error in Redis resulting in a connection closure, there isn't a logic in place to perform a reconnection and potentially recycle the subscribe. I think we are missing a listener for $this->subscriber->on('close') in the RedisTransport's init(), and to handle this issue. We noticed this in practice, in our production environment. Whenever Redis crashes or reboots, Mercure becomes inconsistent and non-functional.

**Comment by bpolaszek** [comment]
Hi @progmancod - would it be possible for you to test [this version](https://github.com/bpolaszek/freddie/pull/25)?
